### PR TITLE
=use WebUtility.HtmlEncode instead of System.Web.HttpUtility

### LINKED ISSUE #4: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Web.HttpUtility' does not contain a definition for 'HtmlEncode'
this issue occurs when an app is published using the library.

 `Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Web.HttpUtility' does not contain a definition for 'HtmlEncode'`

### PR DESCRIPTION
**Pull request by AbanoubNassem**
The `System.Web.HttpUtility` class in .NET Core 6+ no longer includes the HtmlEncode method. Instead, we can use the 
`WebUtility.HtmlEncode` method from the `System.Net namespace` to encode HTML strings.

fixes #4

### CODE REVIEW

File: InertiaCore/ResponseFactory.cs [hunk 1]
```diff
@@ -77,7 +77,7 @@ public async Task<IHtmlContent> Html(dynamic model)
                 ReferenceHandler = ReferenceHandler.IgnoreCycles
             });
 
-        var encoded = HttpUtility.HtmlEncode(data);
+        var encoded =  WebUtility.HtmlEncode(data);
```
Comment (kapi2289) [inline InertiaCore/ResponseFactory.cs:80]:
```suggestion
        var encoded = WebUtility.HtmlEncode(data);
```

Just remove the double space

**Review by kapi2289 — CHANGES_REQUESTED** [review]
OK!

**Review by kapi2289 — APPROVED** [review]
